# Generated by Django 4.2.30 on 2026-05-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomevent',
            name='event',
            field=models.CharField(choices=[('entered', 'Entered'), ('left', 'Left')], max_length=20),
        ),
        migrations.AlterField(
            model_name='faceattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
