# Generated by Django 4.2.30 on 2026-05-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_classroomevent_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomevent',
            name='event',
            field=models.CharField(choices=[('ENTERED', 'ENTERED'), ('LEFT', 'LEFT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='faceattendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'PRESENT'), ('CANCELLED', 'CANCELLED')], max_length=20),
        ),
    ]
